--1. TAO CSDL
	CREATE DATABASE QLBH
	ON PRIMARY
		(NAME = QLBH_data,
		FILENAME = 'T:\DL\QLBH_data.mdf',
		SIZE = 10,
		MAXSIZE = 20,
		FILEGROWTH = 1)
	LOG ON
		(NAME = QLBH_log,
		FILENAME = 'T:\DL\QLBH_log.ldf',
		SIZE = 4,
		MAXSIZE = 10,
		FILEGROWTH = 1)

	GO
	USE QLBH
--2. TAO TABLE
	GO 
	
	CREATE TABLE NHOMSANPHAM
		(MANHOM INT PRIMARY KEY,
		TENNHOM NVARCHAR(15))
	CREATE TABLE NHACUNGCAP
		(MANCC INT PRIMARY KEY,
		TENNCC NVARCHAR(40) NOT NULL,
		DIACHI NVARCHAR(60),
		PHONE NVARCHAR(24),
		SOFAX NVARCHAR(24),
		DCMAIL NVARCHAR(50))

	CREATE TABLE SANPHAM
		(MASP INT PRIMARY KEY,
		TENSP NVARCHAR(40) NOT NULL,
		MANCC INT FOREIGN KEY REFERENCES NHACUNGCAP(MANCC),
		MOTA NVARCHAR(50),
		MANHOM INT FOREIGN KEY REFERENCES NHOMSANPHAM(MANHOM),
		DONVITINH NVARCHAR(20), GIAGOC MONEY)
	
	CREATE TABLE KHACHHANG
		(MAKH CHAR(5) PRIMARY KEY,
		TENKH NVARCHAR(40) NOT NULL,
		LOAIKH NVARCHAR(3) CHECK(LOAIKH IN('VIP','TV','VL')),
		DIACHI NVARCHAR(60),
		PHONE NVARCHAR(24),
		DCMAIL NVARCHAR(50),
		DIEMTL INT CHECK(DIEMTL >= 0))

	CREATE TABLE HOADON
		(MAHD INT PRIMARY KEY,
		NGAYLAPHD DATETIME CHECK(NGAYLAPHD >= GETDATE()) default getdate(),
		NGAGYGIAO DATETIME,
		NOICHUYEN NVARCHAR(60) NOT NULL,
		MAKH CHAR(5) REFERENCES KHACHHANG(MAKH))

	CREATE TABLE CT_HOADON
		(MAHD INT FOREIGN KEY REFERENCES HOADON(MAHD) ,
		MASP INT FOREIGN KEY REFERENCES SANPHAM(MASP),
		PRIMARY KEY(MAHD, MASP),
		SOLUONG SMALLINT CHECK(SOLUONG > 0),
		DONGIA MONEY,
		CHIETKHAU MONEY CHECK(CHIETKHAU >= 0))

	ALTER TABLE HOADON
	ADD CONSTRAINT CC_NGAYLAPHD CHECK(NGAYLAPHD >= GETDATE())

	ALTER TABLE HOADON
	ADD CONSTRAINT CK_NGAYLAPHD DEFAULT GETDATE() FOR NGAYLAPHD

	ALTER TABLE HOADON
	ADD	LOAIHD CHAR(1) CHECK(LOAIHD IN ('N', 'X', 'C', 'T'))

	ALTER TABLE HOADON
	ADD CONSTRAINT DF_LOAIHD DEFAULT 'N' FOR LOAIHD
 
 --3.THEM DU LIEU
	ALTER TABLE NHOMSANPHAM
		ALTER COLUMN TENNHOM NVARCHAR(30)

	ALTER TABLE SANPHAM
		ADD SlTon int
	INSERT NHOMSANPHAM VALUES (1,N'ĐIỆN TỬ'),(2,N'GIA DỤNG'),(3,N'DỤNG CỤ GIA ĐÌNH'),(4,N'CÁC MẶT HÀNG KHÁC')
	SELECT * FROM NHOMSANPHAM

	INSERT NHACUNGCAP VALUES (1,N'CÔNG TY TNHH NAM PHƯƠNG',N'1 Lê Lơi Phường 4 Quận Gò Vấp','08384356', '32343434', 'namphuong@yahoo.com'),
							 (2,N'Công Ty Lan Ngọc', N'12 Cao Bá Quát Quận 1 Tp.Hồ Chí Minh', '086234567','83434355', 'lanngoc@gamil.com')
	SELECT * FROM NHACUNGCAP

	INSERT SANPHAM VALUES (1, N'Máy Tính', '1', N'Máy Sony ram 2GB','1', N'Cái', '7000000', '100'),
						  (2, N'Bàn phím', '1', N'Bàn phím 101 phím', '1',  N'Cái', '1000000', '50'),
						  (3, N'Chuột', '1', N'Chuột không dây', '1', N'Cái', '800000', '150'),
						  (4, N'CPU', '1', N'CPU', '1', N'Cái', '3000000', '200'),
						  (5, N'USE', '1', N'8GB', '1',  N'Cái', '500000', '100'),
						  (6, N'Lò Vi Sóng', '2', NULL,'3',  N'Cái', '1000000', '20')
	SELECT * FROM SANPHAM

	INSERT KHACHHANG VALUES ('KH1', N'Nguyễn Thu Hằng', N'VL', N'12 Nguyễn Du',' ', NULL, NULL),
							( 'KH2', N'Lê Minh', N'TV', N'34 Điện Biên Phủ', N'012394345', N'LeMinh@yahoo.com', 100),
							('KH3', N'Nguyễn Minh Trung', N'VIP', N'3 Lê Lợi Quận Gò Vấp', N'098343434', N'Trung@gamil.com', 800)
	SELECT * FROM KHACHHANG

	SET DATEFORMAT DMY
	INSERT HOADON VALUES (1, '28/09/2023', '30/09/2023', N'Cửa Hàng ABC 3 Lý Chính Thắng Quận 3', 'KH1'),
						 (2, '28/09/2023', '05/10/2023', N'23 Lê Lợi Quận Gò Vấp', 'KH2'),
						 (3, '28/09/2023', '28/09/2023', N'2 Nguyễn Du Quận Gò Vấp', 'KH3')
	SELECT * FROM HOADON

	INSERT CT_HOADON VALUES (1, 1, 5, 8000)